name: Output information
on: workflow_dispatch
jobs:
  info_job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}"
      - name: print custom
        run: |
          echo "${{ github.token }}"
          echo "${{ secrets.GITHUB_TOKEN }}"